### ISSUE TITLE
Traffic Proportion Metrics 

### ISSUE THREAD

**Issue by wSedlacek** [knative-extensions/serving-progressive-rollout#106]
I have been following the progressive rollout features across multiple projects for some time now. I was very interested when I saw this repo as a direct extension to Knative. As I was reading the design document I noticed this question raised and I felt compelled to share (if helpful) some prior art that may be useful.

> Per each stage, how do we detect the end?
I have not found out the way to detect the correct traffic proportion has been really assigned to the revision. For example, I want to distribute 50% of the traffic to Revision A by configuring the Route. Which parameter can we check to indicate there is actually 50% of the traffic going to Revision A? If anyone knows how we can do it, please leave your suggestions here.

In Argo Rollouts there are customizable Analysis Templates which support several providers including prometheus.
https://argoproj.github.io/argo-rollouts/features/analysis/#background-analysis

With the prometheus specific provider you can use `istio_requests_total` (when using istio) to determine the total request and how they are being routed. I believe this is the same datasource that Kiali uses for all it's visualizations.

Flagger also has an integration for Istio and Contour with a `metrics` option in `analysis` named `request-success-rate`. I haven't dived into their source code yet to see where this metric is pulled specifically from but it may be worth investigating.

https://fluxcd.io/flagger/tutorials/istio-progressive-delivery/#bootstrap

I am excited to see where this extension goes! I would love to see more features from Argo Rollouts and Flagger added over time!

**Comment by houshengbo** [comment]
@wSedlacek Thank you for the useful comments and your attention to this repo.

In the design doc, I listed several principles to implement this feature: try to use the existing code or features as much as possible, and try to change the components as few as possible.

I added a similar CRD in this repo to the one `Rollout` that argo uses to manage the progress to shift the traffic, control the percentage and the target number of replicas for each step, until 100% of the traffic has been shifted to the new revision.

You can try out this extension: https://github.com/knative-extensions/serving-progressive-rollout/blob/main/DEVELOPMENT.md based on the serving you installed.

However, we have already cut the release for 1.13: https://github.com/knative-extensions/serving-progressive-rollout/releases/tag/knative-v1.13.3
